// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD37RKXeu9ztpkfFtUzIuoGHthQ1RQQUPo',
    appId: '1:448394998387:web:f5de620aeced6119d73006',
    messagingSenderId: '448394998387',
    projectId: 'fuelgo-d3151',
    authDomain: 'fuelgo-d3151.firebaseapp.com',
    storageBucket: 'fuelgo-d3151.firebasestorage.app',
    measurementId: 'G-C4C8E1LPJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcp8VxTOvF1MHUuAhQex2YzaCnDhTPNhc',
    appId: '1:448394998387:android:31fb996e38e826e8d73006',
    messagingSenderId: '448394998387',
    projectId: 'fuelgo-d3151',
    storageBucket: 'fuelgo-d3151.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAolV_kMZPEs3uAciWblzTQOmQzySBXI70',
    appId: '1:448394998387:ios:f535488fc49dcd0fd73006',
    messagingSenderId: '448394998387',
    projectId: 'fuelgo-d3151',
    storageBucket: 'fuelgo-d3151.firebasestorage.app',
    androidClientId: '448394998387-ee9nop285mblji6dt62akl3v1a0hrat2.apps.googleusercontent.com',
    iosClientId: '448394998387-t9rq348ae4f1ab8hg0o80u5jvcs8s7l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.fuelgo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAolV_kMZPEs3uAciWblzTQOmQzySBXI70',
    appId: '1:448394998387:ios:f535488fc49dcd0fd73006',
    messagingSenderId: '448394998387',
    projectId: 'fuelgo-d3151',
    storageBucket: 'fuelgo-d3151.firebasestorage.app',
    androidClientId: '448394998387-ee9nop285mblji6dt62akl3v1a0hrat2.apps.googleusercontent.com',
    iosClientId: '448394998387-t9rq348ae4f1ab8hg0o80u5jvcs8s7l6.apps.googleusercontent.com',
    iosBundleId: 'com.example.fuelgo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD37RKXeu9ztpkfFtUzIuoGHthQ1RQQUPo',
    appId: '1:448394998387:web:043a00bef6c77b50d73006',
    messagingSenderId: '448394998387',
    projectId: 'fuelgo-d3151',
    authDomain: 'fuelgo-d3151.firebaseapp.com',
    storageBucket: 'fuelgo-d3151.firebasestorage.app',
    measurementId: 'G-XPJM95G5LY',
  );
}
